version: "3.8"
services:
  database:
    image: mysql:5.7.35
    container_name: olist-database
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - 3306:3306
    volumes:
      - olist-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: olist/app
    container_name: olist-app
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./:/app
    restart: always    

# persisted storage
volumes:
  olist-data:
