version: "3.8"
services:
  database:
    image: mysql:5.7.35
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - olist-data:/var/lib/mysql
    container_name: olist-api-db

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./:/app
    

# persisted storage
volumes:
  olist-data:
